// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: inference.proto

#include "inference.pb.h"
#include "inference.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace inference {

static const char* ShapeDetection_method_names[] = {
  "/inference.ShapeDetection/Detect",
};

std::unique_ptr< ShapeDetection::Stub> ShapeDetection::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ShapeDetection::Stub> stub(new ShapeDetection::Stub(channel));
  return stub;
}

ShapeDetection::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Detect_(ShapeDetection_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ShapeDetection::Stub::Detect(::grpc::ClientContext* context, const ::inference::DetectionRequest& request, ::inference::DetectionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Detect_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::inference::DetectionResponse>* ShapeDetection::Stub::AsyncDetectRaw(::grpc::ClientContext* context, const ::inference::DetectionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::inference::DetectionResponse>::Create(channel_.get(), cq, rpcmethod_Detect_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::inference::DetectionResponse>* ShapeDetection::Stub::PrepareAsyncDetectRaw(::grpc::ClientContext* context, const ::inference::DetectionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::inference::DetectionResponse>::Create(channel_.get(), cq, rpcmethod_Detect_, context, request, false);
}

ShapeDetection::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ShapeDetection_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ShapeDetection::Service, ::inference::DetectionRequest, ::inference::DetectionResponse>(
          std::mem_fn(&ShapeDetection::Service::Detect), this)));
}

ShapeDetection::Service::~Service() {
}

::grpc::Status ShapeDetection::Service::Detect(::grpc::ServerContext* context, const ::inference::DetectionRequest* request, ::inference::DetectionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* ObjectDetection_method_names[] = {
  "/inference.ObjectDetection/Detect",
};

std::unique_ptr< ObjectDetection::Stub> ObjectDetection::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ObjectDetection::Stub> stub(new ObjectDetection::Stub(channel));
  return stub;
}

ObjectDetection::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Detect_(ObjectDetection_method_names[0], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::ClientReader< ::inference::Object>* ObjectDetection::Stub::DetectRaw(::grpc::ClientContext* context, const ::inference::DetectionRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::inference::Object>::Create(channel_.get(), rpcmethod_Detect_, context, request);
}

::grpc::ClientAsyncReader< ::inference::Object>* ObjectDetection::Stub::AsyncDetectRaw(::grpc::ClientContext* context, const ::inference::DetectionRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::inference::Object>::Create(channel_.get(), cq, rpcmethod_Detect_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::inference::Object>* ObjectDetection::Stub::PrepareAsyncDetectRaw(::grpc::ClientContext* context, const ::inference::DetectionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::inference::Object>::Create(channel_.get(), cq, rpcmethod_Detect_, context, request, false, nullptr);
}

ObjectDetection::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ObjectDetection_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< ObjectDetection::Service, ::inference::DetectionRequest, ::inference::Object>(
          std::mem_fn(&ObjectDetection::Service::Detect), this)));
}

ObjectDetection::Service::~Service() {
}

::grpc::Status ObjectDetection::Service::Detect(::grpc::ServerContext* context, const ::inference::DetectionRequest* request, ::grpc::ServerWriter< ::inference::Object>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace inference

